backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: src/assets/images/blog # Location where files will be stored in the repo
public_folder: public/  # The src attribute for uploaded media
site_url: https://intermediate-astro-kit-decap-cms.netlify.app/ # Displays a link to home page in the top-right corner of the CMS dashboard

collections:
  - name: "updates" # Used in routes, e.g., /admin/collections/blog
    label: "Updates" # Used in the UI
    folder: "src/components/sections/home/Updates.astro" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Description", name: "description", widget: "text" }
     